window.ENV_SUPABASE_URL = 'https://kkseqhmfubzfyloffkwe.supabase.co';
window.ENV_SUPABASE_ANON_KEY = 'sb_publishable_PUSXT6qIH0IoeEgKQ3hgbA_m8hYY4Dv';
window.ENV_BERATER_ID = 'b3cbf981-ea3e-4e6d-a993-2fe158ca0d48';
window.ENV_WHATSAPP = '4915154776159';
window.ENV_BERATER_NAME = 'Kai Blobel';
window.ENV_BERATER_TITEL = 'Regionaldirektion · Team Wachsbleiche';
window.ENV_BERATER_FOTO = '/assets/images/kai-portrait.jpg';
window.ENV_CALENDLY_URL = ''; // sobald Kai einen Link schickt, hier eintragen — Karte erscheint automatisch
window.APP_VERSION = 'v1.128 Beta';
window.APP_PHASE = 'Phase 98 · Emotionale Bildwelten im Finanzierungskompass';
