-- ============================================================================
-- schema-phase116.sql · Phase 116 · Doppelte Programm-Inhalte entfernen
-- ----------------------------------------------------------------------------
-- STATUS: LIVE angewandt am 2026-08-04. Version v1.142.
--
-- Vorlagen, Belohnungen und Erfolgsgeschichten sind EIN geteilter Satz, den
-- alle Berater zeigen. Am 23.07.2026 kam beim Anlegen des Beraters
-- "Max Kudlek" (7b176742-…, ist_aktiv = false) ein kompletter zweiter Satz in
-- die Tabellen. Weil die Lese-Policies alle Zeilen öffentlich freigeben, stand
-- danach jede Belohnung, jede Themenwelt und jede Erfolgsgeschichte doppelt:
-- in der Präsentation, im Empfehlungs-Formular, im Promoter-Bereich, in den
-- Admin-Editoren und auf der Empfänger-Seite.
--
-- Der Client filtert Dubletten seit v1.142 zusätzlich weg (eineZeileProSchluessel
-- in js/supabase.js). Dieses Skript beseitigt die Ursache.
--
-- Geprüft vor dem Löschen:
--   * kein Fremdschlüssel zeigt auf belohnungs_stufen
--   * Max Kudlek hat 0 Promoter, 0 Empfehlungen, 0 Prämien
--   * alle Zeilen sind inhaltsgleiche Kopien der Zeilen von Kai Blobel
-- ============================================================================

delete from public.belohnungs_stufen  where berater_id = '7b176742-7b1a-4555-ba90-c5f6041fe4e1';  -- 7 Zeilen
delete from public.vorlagen           where berater_id = '7b176742-7b1a-4555-ba90-c5f6041fe4e1';  -- 8 Zeilen
delete from public.erfolgsgeschichten where berater_id = '7b176742-7b1a-4555-ba90-c5f6041fe4e1';  -- 3 Zeilen

-- Erwartet danach: belohnungs_stufen 7, vorlagen 8, erfolgsgeschichten 3
-- select count(*) from public.belohnungs_stufen;

-- ============================================================================
-- ROLLBACK — falls Max Kudlek doch wieder aktiv wird, diesen Block ausführen.
-- Stand der Zeilen zum Zeitpunkt des Löschens (2026-08-04).
-- ============================================================================
/*
insert into public.belohnungs_stufen (stufe, titel, beschreibung, icon, wert_label, highlight, sort_order, bild_url, berater_id, kategorien) values (1, 'Empfehlungs-Bonus', '100 € als Wunschgutschein, PayPal-Auszahlung oder Spende deiner Wahl.', '🎟️', NULL, 'f', 1, '/assets/images/programm/kundenlos.jpg', '7b176742-7b1a-4555-ba90-c5f6041fe4e1'::uuid, '{geld,spende}'::text[]);
insert into public.belohnungs_stufen (stufe, titel, beschreibung, icon, wert_label, highlight, sort_order, bild_url, berater_id, kategorien) values (2, 'Restaurantbesuch deiner Wahl', 'Du und eine Begleitperson genießen einen Restaurantbesuch nach Wahl.', '🍽️', '150 €', 'f', 2, '/assets/images/programm/restaurant.jpg', '7b176742-7b1a-4555-ba90-c5f6041fe4e1'::uuid, '{sache}'::text[]);
insert into public.belohnungs_stufen (stufe, titel, beschreibung, icon, wert_label, highlight, sort_order, bild_url, berater_id, kategorien) values (3, 'Empfehlungs-Bonus', 'Wieder 100 € als Wunschgutschein, PayPal-Auszahlung oder Spende deiner Wahl.', '🎟️', '100 €', 'f', 3, '/assets/images/programm/standard.jpg', '7b176742-7b1a-4555-ba90-c5f6041fe4e1'::uuid, '{geld,spende}'::text[]);
insert into public.belohnungs_stufen (stufe, titel, beschreibung, icon, wert_label, highlight, sort_order, bild_url, berater_id, kategorien) values (5, 'Weber-Grill oder Apple Watch', 'Wähle zwischen einem Weber Gasgrill oder der aktuellen Apple Watch.', '🍖', '449 €', 'f', 4, '/assets/images/programm/applewatch.jpg', '7b176742-7b1a-4555-ba90-c5f6041fe4e1'::uuid, '{sache}'::text[]);
insert into public.belohnungs_stufen (stufe, titel, beschreibung, icon, wert_label, highlight, sort_order, bild_url, berater_id, kategorien) values (7, 'Goldbarren im Wert von 500 €', 'Ein echter Goldbarren im Wert von 500 €. Werterhalt zum Anfassen, den du behältst.', '🥇', '500 €', 'f', 5, '/assets/images/programm/goldbarren.jpg', '7b176742-7b1a-4555-ba90-c5f6041fe4e1'::uuid, '{sache}'::text[]);
insert into public.belohnungs_stufen (stufe, titel, beschreibung, icon, wert_label, highlight, sort_order, bild_url, berater_id, kategorien) values (10, 'iPad Air', 'Das iPad Air – eines der vielseitigsten Tablets auf dem Markt.', '📱', '699 €', 'f', 6, '/assets/images/programm/ipad.jpg', '7b176742-7b1a-4555-ba90-c5f6041fe4e1'::uuid, '{sache}'::text[]);
insert into public.belohnungs_stufen (stufe, titel, beschreibung, icon, wert_label, highlight, sort_order, bild_url, berater_id, kategorien) values (15, 'Mallorca-Urlaub', 'Auf meine Kosten – mit einer Begleitperson nach Mallorca, Sonne inklusive.', '✈️', '2.000 €', 't', 7, '/assets/images/programm/mallorca.jpg', '7b176742-7b1a-4555-ba90-c5f6041fe4e1'::uuid, '{sache}'::text[]);

insert into public.erfolgsgeschichten (id, vorlage_slug, titel, vorher, nachher, key_metric, sort_order, aktiv, created_at, berater_id) values ('92357efd-c2b2-4c8e-89d6-e8f350ebc9ed'::uuid, NULL, 'Familie mit zwei Kindern', 'Riester-Zulagen wurden seit Jahren nicht beantragt.', 'Volle staatliche Förderung jetzt aktiv — rückwirkend.', '+ 532 € pro Jahr', 1, 't', '2026-07-23 21:53:33.188944'::timestamp, '7b176742-7b1a-4555-ba90-c5f6041fe4e1'::uuid);
insert into public.erfolgsgeschichten (id, vorlage_slug, titel, vorher, nachher, key_metric, sort_order, aktiv, created_at, berater_id) values ('2bad37ef-60fb-41c2-9462-35562ae11498'::uuid, NULL, 'Häuslebauer im Sauerland', 'Anschlussfinanzierung zu Standard-Konditionen.', 'Optimierte Struktur mit besserer Zinsbindung.', '~ 18.400 € weniger Zinslast', 2, 't', '2026-07-23 21:53:33.188944'::timestamp, '7b176742-7b1a-4555-ba90-c5f6041fe4e1'::uuid);
insert into public.erfolgsgeschichten (id, vorlage_slug, titel, vorher, nachher, key_metric, sort_order, aktiv, created_at, berater_id) values ('6b3cf245-3af8-46fe-b699-b107ceac7c64'::uuid, NULL, 'Selbstständiger Berater', 'Keine Altersvorsorge mit Steuerhebel.', 'Basisrente mit voller Absetzbarkeit aufgesetzt.', '4.200 € Steuervorteil im ersten Jahr', 3, 't', '2026-07-23 21:53:33.188944'::timestamp, '7b176742-7b1a-4555-ba90-c5f6041fe4e1'::uuid);

insert into public.vorlagen (id, slug, titel, icon, headline, subtext, hero_bild_url, quickcheck_url, vorteil_1_titel, vorteil_1_text, vorteil_2_titel, vorteil_2_text, vorteil_3_titel, vorteil_3_text, cta_text, aktiv, sort_order, created_at, berater_id, hook_text, in_arbeit) values ('beac6315-bed8-4a02-9c00-d5913174b731'::uuid, 'allgemein', 'Allgemein', 'Compass', 'Was liegt bei dir gerade rum?', 'Die meisten verschenken jeden Monat Geld, ohne es zu merken: bei Steuer, Förderung oder Verträgen, die längst besser gingen. In einem kurzen Gespräch finden wir, wo das bei dir der Fall ist.', 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&q=80', 'https://finanzcheck.kaiblobel.de/', 'Dein Zahlen-Bild', 'Du siehst auf einen Blick, wo du stehst und wo bei dir konkret Geld liegen bleibt.', 'Bares Potenzial', 'Förderungen, Steuervorteile und bessere Konditionen, von denen die meisten nicht wissen, dass sie ihnen zustehen.', 'Auf dein Leben gerechnet', 'Keine Standard-Tipps. Was in deiner Situation wirklich etwas bringt.', 'Zeig mir, was bei mir drin ist →', 't', 0, '2026-07-23 21:53:33.188944'::timestamp, '7b176742-7b1a-4555-ba90-c5f6041fe4e1'::uuid, 'Allein Förderung und ein paar Steuerhebel bringen vielen mehrere hundert Euro im Jahr, die sie liegen lassen, weil es nie jemand ausgerechnet hat. Die Frage ist nicht, ob bei dir etwas zu holen ist, sondern wie viel. Genau das siehst du im Check in ein paar Minuten schwarz auf weiß.', 't');
insert into public.vorlagen (id, slug, titel, icon, headline, subtext, hero_bild_url, quickcheck_url, vorteil_1_titel, vorteil_1_text, vorteil_2_titel, vorteil_2_text, vorteil_3_titel, vorteil_3_text, cta_text, aktiv, sort_order, created_at, berater_id, hook_text, in_arbeit) values ('0d574d5a-2e69-49ef-988f-f0acf636bde4'::uuid, 'baufi', 'Baufinanzierung', 'Home', 'Eine Analyse, 402 Banken.', 'Ob Neubau, Kauf oder Anschlussfinanzierung: Eine Finanzierung begleitet dich oft über Jahrzehnte. Gut, wenn vorher jemand mit dir ruhig auf die ganze Laufzeit schaut, nicht nur auf den ersten Zins.', 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80', 'https://baufinanzierung.kaiblobel.de', '402 Banken, eine Analyse', 'Eine einzige Immobilienanalyse vergleicht für dich die Möglichkeiten von 402 Banken. Du läufst nicht von Filiale zu Filiale.', 'Ein Ansprechpartner', 'Von der ersten Idee bis zur Schlüsselübergabe begleitet dich eine Person, kein wechselndes Team.', 'Die ganze Laufzeit im Blick', 'Wir schauen nicht nur auf die erste Zinsbindung, sondern auf die gesamte Zeit bis dein Kredit getilgt ist.', 'Immobilienanalyse öffnen', 't', 1, '2026-07-23 21:53:33.188944'::timestamp, '7b176742-7b1a-4555-ba90-c5f6041fe4e1'::uuid, 'Die meisten holen ein, zwei Angebote von der eigenen Bank ein. Über eine einzige Immobilienanalyse schauen wir gemeinsam auf 402 Banken.', 't');
insert into public.vorlagen (id, slug, titel, icon, headline, subtext, hero_bild_url, quickcheck_url, vorteil_1_titel, vorteil_1_text, vorteil_2_titel, vorteil_2_text, vorteil_3_titel, vorteil_3_text, cta_text, aktiv, sort_order, created_at, berater_id, hook_text, in_arbeit) values ('35f1572d-4106-459f-af74-943949ec6524'::uuid, 'foerderungen', 'Staatliche Förderungen', 'Banknote', 'Rechne deine Förderung selbst nach.', 'Riester, vermögenswirksame Leistungen, Arbeitnehmer-Sparzulage: Es gibt einige Töpfe vom Staat und vom Arbeitgeber. Welche davon für dich infrage kommen, hängt von deiner Situation ab. Genau das schauen wir uns in Ruhe gemeinsam an.', 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200&q=80', 'https://finanzcheck.kaiblobel.de/', 'Was für dich infrage kommt', 'Wir gehen die staatlichen und betrieblichen Töpfe durch und schauen, welche in deiner Situation möglich wären.', 'Auch rückwirkend', 'Manche Förderungen lassen sich noch fürs laufende Jahr sichern. Wir prüfen in Ruhe, was bei dir machbar wäre.', 'Ohne Papierkram-Frust', 'Ich sage dir, welche Unterlagen du brauchst und wie der Antrag läuft. Du musst dich nicht durch Formulare quälen.', 'Förderrechner öffnen', 't', 2, '2026-07-23 21:53:33.188944'::timestamp, '7b176742-7b1a-4555-ba90-c5f6041fe4e1'::uuid, 'Viele lassen Jahr für Jahr Förderung liegen, einfach weil es ihnen nie jemand ausgerechnet hat.', 't');
insert into public.vorlagen (id, slug, titel, icon, headline, subtext, hero_bild_url, quickcheck_url, vorteil_1_titel, vorteil_1_text, vorteil_2_titel, vorteil_2_text, vorteil_3_titel, vorteil_3_text, cta_text, aktiv, sort_order, created_at, berater_id, hook_text, in_arbeit) values ('07a42956-f59e-4bf9-9281-940d5e6902b9'::uuid, 'selbstaendige', 'Selbständige', 'Briefcase', 'Selbständig. Abgesichert. Vorgesorgt.', 'Als Selbständiger hast du keine automatische Absicherung. Wir bauen gemeinsam ein stabiles Fundament.', 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=1200&q=80', 'https://finanzcheck.kaiblobel.de/', 'Basisrente', 'Bis zu 100% der Beiträge steuerlich absetzen — der größte Hebel für Selbständige.', 'Berufsunfähigkeit', 'Dein wichtigstes Kapital bist du selbst. Wir sichern deine Arbeitskraft ab.', 'Liquidität erhalten', 'Vorsorge die zu deinen Cashflows passt — flexibel und planbar.', 'Meine Situation als Selbständiger prüfen →', 't', 3, '2026-07-23 21:53:33.188944'::timestamp, '7b176742-7b1a-4555-ba90-c5f6041fe4e1'::uuid, NULL, 't');
insert into public.vorlagen (id, slug, titel, icon, headline, subtext, hero_bild_url, quickcheck_url, vorteil_1_titel, vorteil_1_text, vorteil_2_titel, vorteil_2_text, vorteil_3_titel, vorteil_3_text, cta_text, aktiv, sort_order, created_at, berater_id, hook_text, in_arbeit) values ('7eabe0d5-f028-4470-8de4-74036f1811b2'::uuid, 'investment', 'Geldanlage & Investment', 'TrendingUp', 'Was dein Geld über die Jahre tun kann.', 'Auf dem Konto verliert dein Geld still und leise an Kaufkraft. Du musst kein Finanzprofi sein, um das zu ändern. Wir schauen gemeinsam, was zu deinem Leben passt.', 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1200&q=80', 'https://finanzcheck.kaiblobel.de/', 'Begleitung, die bleibt', 'Ein Ansprechpartner, immer derselbe. Einer, der deine Situation kennt und sich täglich damit beschäftigt.', 'Kein Schema F', 'Kein Produkt für alle. Je nach Situation aus Fonds, Versicherungslösungen, Gold oder Anleihen, was zu dir passt.', 'Den Überblick behalten', 'Förderungen, Steuervorteile, staatliche Zulagen: Wir schauen gemeinsam, welche davon du nutzen kannst.', 'Anlage-Möglichkeiten ansehen', 't', 4, '2026-07-23 21:53:33.188944'::timestamp, '7b176742-7b1a-4555-ba90-c5f6041fe4e1'::uuid, 'Du musst auch nicht viel Geld übrig haben. Manche fangen mit 50 Euro im Monat an, andere mit mehr. Beides ist ein Anfang.', 't');
insert into public.vorlagen (id, slug, titel, icon, headline, subtext, hero_bild_url, quickcheck_url, vorteil_1_titel, vorteil_1_text, vorteil_2_titel, vorteil_2_text, vorteil_3_titel, vorteil_3_text, cta_text, aktiv, sort_order, created_at, berater_id, hook_text, in_arbeit) values ('c5482b8b-6083-4bc7-8acc-f68518b28c04'::uuid, 'absicherung', 'Absicherung & Familie', 'ShieldCheck', 'Was wirklich wichtig ist. Abgesichert.', 'Familie, Gesundheit, Arbeitskraft — wir schauen gemeinsam was wirklich geschützt sein muss und was nicht.', 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=1200&q=80', 'https://finanzcheck.kaiblobel.de/', 'Berufsunfähigkeit', 'Die wichtigste Versicherung die die meisten nicht haben. Wir klären ob du sie brauchst.', 'Familie absichern', 'Was passiert mit deiner Familie wenn du ausfällst? Wir geben Antworten.', 'Nur was nötig ist', 'Keine Überversicherung. Wir streichen was unnötig ist und sichern was wirklich zählt.', 'Meine Absicherung prüfen →', 't', 5, '2026-07-23 21:53:33.188944'::timestamp, '7b176742-7b1a-4555-ba90-c5f6041fe4e1'::uuid, NULL, 't');
insert into public.vorlagen (id, slug, titel, icon, headline, subtext, hero_bild_url, quickcheck_url, vorteil_1_titel, vorteil_1_text, vorteil_2_titel, vorteil_2_text, vorteil_3_titel, vorteil_3_text, cta_text, aktiv, sort_order, created_at, berater_id, hook_text, in_arbeit) values ('a45efcbe-5224-482f-a487-c08a21d7f9bd'::uuid, 'karriere', 'Berufliche Perspektive', 'Sparkles', 'Bereit, was Eigenes zu machen?', 'Eine berufliche Perspektive, die mehr Sinn, mehr Selbstbestimmung und finanzielle Freiheit bringt. Hier könnte dein Weg neu beginnen.', 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1200&q=80&auto=format&fit=crop', 'https://karrierecheck.kaiblobel.de', 'Vom ersten Tag verdienen', '4.500 € im Monat sind möglich, plus 750 € Förderung pro Monat. Sicherer Einstieg ohne Sprung ins kalte Wasser.', 'Klare Perspektive', 'Ausbildung, Coaching, eigener Weg. Du baust dir Schritt für Schritt etwas Eigenes auf, mit voller Unterstützung von Anfang an.', 'Sinnvolle Arbeit', 'Menschen dabei helfen, ihre Finanzen zu sortieren. Echter Mehrwert statt Excel-Sklaverei.', 'Karriere-Check starten', 't', 6, '2026-07-23 21:53:33.188944'::timestamp, '7b176742-7b1a-4555-ba90-c5f6041fe4e1'::uuid, NULL, 't');
insert into public.vorlagen (id, slug, titel, icon, headline, subtext, hero_bild_url, quickcheck_url, vorteil_1_titel, vorteil_1_text, vorteil_2_titel, vorteil_2_text, vorteil_3_titel, vorteil_3_text, cta_text, aktiv, sort_order, created_at, berater_id, hook_text, in_arbeit) values ('3e2790e6-ccae-48eb-9925-d12d4f10e243'::uuid, 'kinder', 'Für deine Kinder', 'Heart', 'Früh starten. Später danken sie es dir.', 'Ausbildung, Führerschein, erstes Auto, Studium — wer früh anfängt, baut mit kleinen Beiträgen ein echtes Polster auf. Kindergeld und staatliche Zulagen lassen sich dabei clever mitnehmen.', NULL, 'https://finanzcheck.kaiblobel.de/', 'Früh anfangen', 'Schon kleine Beiträge wachsen über die Jahre zu einem großen Polster.', 'Zinseszins nutzen', 'Je länger die Laufzeit, desto stärker arbeitet der Zinseszins für dein Kind.', 'Förderung mitnehmen', 'Kinderzulagen und staatliche Förderung clever kombiniert.', 'Mehr für mein Kind herausholen', 't', 7, '2026-07-23 21:53:33.188944'::timestamp, '7b176742-7b1a-4555-ba90-c5f6041fe4e1'::uuid, NULL, 't');
*/
